#!/usr/bin/awk -f

# ksampler - a random subset picker for tabular data built in awk
#   author - github.com/rtrigoso
#   web    - https://renfoc.us
# --------------------------------------------------------------------
# Usage: 
#   rowbot -n 20 tabular_data.csv
#     > outputs 20 random row entries
# --------------------------------------------------------------------
# ARGC = count of arguments
# ARGV = arguments array, starts from 0

BEGIN {
  if (ARGC < 2)
    exit "missing required inputs"
  
  k = 1
  i = 1
  l = 1
  
  for (x = 1; x < ARGC; x++){
	if (ARGV[i] ~ /\-n=?[0-9]+/) {
	  l++
	  k = substr(ARGV[i],3,length(ARGV[i]))
	  delete ARGV[x]
	}
  }
	
  ARGC = length(ARGV)
}
NR <= k {
  r[i] = $0
}
{
  x = srand() * 100000000
  y = NR
  z = int(x % y) < k

  if (z == 1) {
	r[i] = NR " " $0
  }
  
  i++;
}
i > k {
  i = 1
}
END {
  j = 1
  while (j <= length(r)) {
	print r[j]
	j++
  }
}

